version: "0.2"
words:
  - buchungapp
  - nawadi
  - clsx
  - esbenp
  - headlessui
  - Initatiefnemers
  - PGURI
  - pnpx
  - ryanluker
  - skreet
  - supabase
  - tailwindcss
  - trivago
  - diplomeringslijn
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
files:
  - "**"
enableFiletypes:
  - "*"
dictionaries:
  - sql
  - nl-nl
import:
  - "@cspell/dict-nl-nl/cspell-ext.json"
