version: '0.2'
words:
  - ABCDEFGHJKLMNPQRSTVWXY
  - afrondingsdag
  - BCDFGHJKLMNPQRT
  - buchungapp
  - clsx
  - diplomeringslijn
  - esbenp
  - Gelicentieerd
  - HACCP
  - headlessui
  - HISWA
  - ianvs
  - Imuqgg
  - INGB
  - INGBNL
  - intructeursdiploma's
  - Krekt
  - kwaliteitspeilers
  - lpignore
  - migra
  - mintlify
  - nawadi
  - nums
  - onnotice
  - otel
  - Outro
  - pgadmin
  - PGURI
  - pkce
  - pkey
  - plpgsql
  - pnpx
  - Polyvalk
  - qrcode
  - redocly
  - rehype
  - ryanluker
  - sadd
  - sindresorhus
  - skiffa
  - skreet
  - smembers
  - solvebv
  - sonner
  - supabase
  - svgs
  - tailwindcss
  - Tera
  - trivago
  - upstash
  - veiligheids
  - Wavie
  - Wbcdfghjkmnpqrtwz
  - WQGR
  - Wytse
  - Zabcdefghijkmnpqrstvwxyz
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
  - spandiensten
  - PDF
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
  - apps/docs/
  - '*.svg'
  - supabase/config.toml
  - packages/db/migrations/
  - locations.ts
  - packages/scripts/src/**/*.txt
files:
  - '**'
enableFiletypes:
  - '*'
dictionaries:
  - sql
  - nl-nl
import:
  - '@cspell/dict-nl-nl/cspell-ext.json'
