version: '0.2'
words:
  - ABCDEFGHJKLMNPQRSTVWXY
  - BCDFGHJKLMNPQRT
  - buchungapp
  - clsx
  - diplomeringslijn
  - esbenp
  - Gelicentieerd
  - HACCP
  - headlessui
  - ianvs
  - Imuqgg
  - INGB
  - INGBNL
  - intructeursdiploma's
  - Krekt
  - kwaliteitspeilers
  - lpignore
  - migra
  - mintlify
  - nawadi
  - nums
  - onnotice
  - Outro
  - pgadmin
  - PGURI
  - pkce
  - plpgsql
  - pnpx
  - redocly
  - rehype
  - ryanluker
  - sindresorhus
  - skreet
  - solvebv
  - supabase
  - svgs
  - tailwindcss
  - trivago
  - veiligheids
  - Wavie
  - Wbcdfghjkmnpqrtwz
  - WQGR
  - Wytse
  - Zabcdefghijkmnpqrstvwxyz
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
  - spandiensten
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
  - apps/docs/
  - '*.svg'
  - supabase/config.toml
  - packages/db/migrations/
files:
  - '**'
enableFiletypes:
  - '*'
dictionaries:
  - sql
  - nl-nl
import:
  - '@cspell/dict-nl-nl/cspell-ext.json'
