version: "0.2"
words:
  - ABCDEFGHJKLMNPQRSTVWXY
  - afrondingsdag
  - atleastone
  - Axwo
  - BCDFGHJKLMNPQRT
  - brondbestand
  - Buchung
  - buchungapp
  - clsx
  - Dehler
  - diplomeringslijn
  - esbenp
  - Gelicentieerd
  - ggik
  - HACCP
  - headlessui
  - hgetall
  - HISWA
  - HLVXVGGi
  - hset
  - ianvs
  - Impersonatie
  - impersoneren
  - Imuqgg
  - INGB
  - INGBNL
  - intructeursdiploma's
  - isail
  - kfwvxetvsoujgiighiqx
  - Krekt
  - kwaliteitspeilers
  - lpignore
  - marifonie
  - migra
  - mintlify
  - nawadi
  - nums
  - nuqs
  - onnotice
  - otel
  - Outro
  - pgadmin
  - PGURI
  - pkce
  - pkey
  - plpgsql
  - pnpx
  - Polyvalk
  - pvbs
  - qrcode
  - qwkkmc
  - redocly
  - rehype
  - ryanluker
  - sadd
  - sindresorhus
  - skiffa
  - skreet
  - smembers
  - solvebv
  - sonner
  - spreadsheetml
  - Suhw
  - supabase
  - svgs
  - tailwindcss
  - techmaus
  - Tera
  - TKFT
  - trivago
  - uncategorized
  - upstash
  - veiligheids
  - VWDS
  - Wavie
  - Wbcdfghjkmnpqrtwz
  - wingfoilen
  - WQGR
  - Wytse
  - ylqt
  - Zabcdefghijkmnpqrstvwxyz
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
  - spandiensten
  - PDF
  - GEWICHTSTRIM
  - PICO
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
  - apps/docs/
  - "*.svg"
  - supabase/config.toml
  - packages/db/migrations/
  - locations.ts
  - packages/scripts/src/**/*.txt
  - packages/scripts/src/seed/countries.ts
  - scripts/seed-local-db.js
  - certificate-templates.ts
files:
  - "**"
enableFiletypes:
  - "*"
dictionaries:
  - sql
  - nl-nl
import:
  - "@cspell/dict-nl-nl/cspell-ext.json"
