version: '0.2'
words:
  - buchungapp
  - clsx
  - diplomeringslijn
  - esbenp
  - HACCP
  - headlessui
  - ianvs
  - Imuqgg
  - INGB
  - INGBNL
  - intructeursdiploma's
  - Krekt
  - kwaliteitspeilers
  - lpignore
  - nawadi
  - nums
  - onnotice
  - Outro
  - PGURI
  - pnpx
  - rehype
  - ryanluker
  - skreet
  - solvebv
  - supabase
  - tailwindcss
  - trivago
  - veiligheids
  - Wavie
  - WQGR
  - Wytse
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
  - spandiensten
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
  - '*.svg'
  - supabase/config.toml
files:
  - '**'
enableFiletypes:
  - '*'
dictionaries:
  - sql
  - nl-nl
import:
  - '@cspell/dict-nl-nl/cspell-ext.json'
