version: '0.2'
words:
  - buchungapp
  - clsx
  - diplomeringslijn
  - esbenp
  - headlessui
  - ianvs
  - INGB
  - INGBNL
  - Krekt
  - nawadi
  - Outro
  - PGURI
  - pnpx
  - ryanluker
  - skreet
  - solvebv
  - supabase
  - tailwindcss
  - trivago
  - veiligheids
  - Wavie
  - Wytse
ignoreWords:
  - TERMS
  - transform
  - BUT
  - LOSS
allowCompoundWords: true
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - generated/
  - apps/nwd-web/src/app/
files:
  - '**'
enableFiletypes:
  - '*'
dictionaries:
  - sql
  - nl-nl
import:
  - '@cspell/dict-nl-nl/cspell-ext.json'
