packages:
  - generated/*
  - packages/lib
  - packages/db
  - packages/core
  - packages/scripts
  - apps/api-server
  - apps/web
  - apps/docs
  - supabase
catalog:
  "@tsconfig/node22": 22.0.0
  "@types/node": 22.7.7
  typescript: 5.6.3

  postgres: "^3.4.4"
  zod: 3.23.8
  drizzle-kit: 0.30.1
  drizzle-orm: 0.38.3

  next: 15.4.0-canary.4
  nuqs: 2.4.0
  react: 19.2.1
  react-dom: 19.2.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3

  "@types/pg": 8.11.11
  pg: 8.13.1