packages:
  - generated/*
  - packages/lib
  - packages/db
  - packages/core
  - packages/scripts
  - apps/api-server
  - apps/web
  - apps/docs
  - supabase
catalog:
  "@tsconfig/node22": 22.0.5
  "@types/node": 22.15.3
  typescript: 5.8.3

  postgres: 3.4.7
  zod: 3.24.4
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1

  next: 16.1.6
  nuqs: 2.4.3
  react: 19.2.4
  react-dom: 19.2.4
  "@types/react": 19.2.10
  "@types/react-dom": 19.2.3

  "@types/pg": 8.16.0
  pg: 8.13.1