packages:
  - generated/*
  - packages/lib
  - packages/db
  - packages/core
  - packages/scripts
  - apps/api-server
  - apps/web
  - apps/docs
  - supabase
catalog:
  typescript: 5.6.3
  zod: 3.23.8
