export const RESET = '\x1b[0m'
export const BOLD = '\x1b[1m'
export const UNDERLINE = '\x1b[4m'
export const INVERSE = '\x1b[7m'

export const TEXT_BLACK = '\x1b[30m'
export const TEXT_RED = '\x1b[31m'
export const TEXT_GREEN = '\x1b[32m'
export const TEXT_YELLOW = '\x1b[33m'
export const TEXT_BLUE = '\x1b[34m'
export const TEXT_MAGENTA = '\x1b[35m'
export const TEXT_CYAN = '\x1b[36m'
export const TEXT_WHITE = '\x1b[37m'
export const TEXT_GRAY = '\x1b[90m'

export const BG_Black = '\x1b[40m'
export const BG_RED = '\x1b[41m'
export const BG_GREEN = '\x1b[42m'
export const BG_YELLOW = '\x1b[43m'
export const BG_BLUE = '\x1b[44m'
export const BG_MAGENTA = '\x1b[45m'
export const BG_CYAN = '\x1b[46m'
export const BG_WHITE = '\x1b[47m'
export const BG_GRAY = '\x1b[100m'
