export const locations = [
  {
    id: 1,
    name: "Zeilschool De Veenhoop",
    placeId: "ChIJL5dM1A1XyEcRVYXYz5_37fI",
    url: "https://zeilschoolfriesland.nl/",
    social_media: {
      facebook: "https://www.facebook.com/zeilschooldeveenhoop",
      instagram: "https://www.instagram.com/zeilschooldeveenhoop",
      tiktok: "https://www.tiktok.com/@zeilschooldeveenhoop",
    },
  },
  {
    id: 2,
    name: "Zeilschool de Kikkert",
    placeId: "ChIJFYhMOAqNyEcRWC2DmWsMy8c",
    url: "https://www.dekikkert.nl/",
    social_media: {
      facebook: "https://www.facebook.com/ZeilschoolDeKikkert",
      instagram: "https://www.instagram.com/de_kikkert/",
      tiktok: "https://www.tiktok.com/@zeilschooldekikkert",
      whatsapp: "https://wa.me/31623851370",
      youtube: "https://www.youtube.com/channel/UCRKY15xGCTmqGSQQZpTBY2Q",
    },
  },
  {
    id: 3,
    name: "Zeilschool Het Molenhuis",
    placeId: "ChIJlw8CVJzyyEcRVLpOria3qqw",
    url: "https://zeilschoolhetmolenhuis.com/",
    social_media: {
      facebook: "https://www.facebook.com/Zeilschoolmolenhuis/",
      instagram: "https://www.instagram.com/zeilschoolhetmolenhuis/",
      tiktok: "https://www.tiktok.com/@zeilschoolhetmolenhuis",
      whatsapp: "https://wa.me/31646026715",
      youtube: "https://www.youtube.com/channel/UCiK6e6hiwMVvG4ekaRWiQKg",
    },
  },
  {
    id: 4,
    name: "Zeilschool Wavie",
    placeId: "ChIJTZvPRNfNxUcRQfqmd00UEZI",
    url: "https://www.wavie.nl/",
    social_media: {
      facebook: "https://www.facebook.com/WavieWavie/",
      instagram: "https://www.instagram.com/zeilschoolwavie/",
      whatsapp: "https://wa.me/31613777345",
      youtube: "https://www.youtube.com/channel/UCGspg9imO9zmI1TlOATcdcw",
    },
  },
  {
    id: 5,
    name: "Krekt Sailing",
    placeId: "ChIJu8nJ_qPxyEcRBZz9Q-I53X8",
    url: "https://www.krektsailing.nl/",
    social_media: {
      facebook: "https://www.facebook.com/KrektSailing/",
      instagram: "https://www.instagram.com/krekt_sailing/",
      youtube: "https://www.youtube.com/user/KrektSailing",
      whatsapp: "https://wa.me/message/X6LUCNAYOOWTC1",
    },
  },
  {
    id: 6,
    name: "Zeil- en Surfschool Neptunus",
    placeId: "ChIJE7fC8UHzyEcRg6Z_k945dHc",
    url: "https://www.zeilschoolneptunus.nl/",
    social_media: {
      facebook: "https://www.facebook.com/zeilschool",
      instagram: "https://www.instagram.com/zeilschoolneptunus/",
      tiktok: "https://www.tiktok.com/@zeilschoolneptunus",
      youtube: "https://www.youtube.com/user/ZeilschoolNeptunusIH",
    },
  },
  {
    id: 7,
    name: "Zeilschool Aalsmeer",
    placeId: "ChIJqWp-nRHexUcRKki3ikC_cBU",
    url: "https://www.zeilschoolaalsmeer.nl/",
    social_media: {
      facebook: "https://www.facebook.com/zeilschoolaalsmeer",
      instagram: "https://www.instagram.com/zeilschoolaalsmeer/",
    },
  },
  {
    id: 8,
    name: "Zeilschool Pean",
    placeId: "ChIJVSQtsAT4yEcRkgqO2iVBz3w",
    url: "https://www.pean.nl/",
    social_media: {
      facebook: "https://www.facebook.com/ZeilschoolPean",
      instagram: "https://www.instagram.com/zeilschoolpean",
      tiktok: "https://www.tiktok.com/@zeilschoolpean",
      youtube: "https://www.youtube.com/channel/UCYZldSSzyHH6mI2Ny_tM_LA/feed",
    },
  },
  {
    id: 9,
    name: "Zeilschool Vinkeveen",
    placeId: "ChIJKX9DlYd0xkcREK8eqdvWQ00",
    url: "https://www.zeilschoolvinkeveen.nl",
    social_media: {
      facebook: "https://www.facebook.com/ZeilschoolVinkeveen",
      instagram: "https://www.instagram.com/zeilschool_vinkeveen/",
      tiktok: "https://www.tiktok.com/@zeilschool_vinkeveen",
    },
  },
] as const;
