openapi: 3.0.2

info:
  title: Nationaal Watersportdiploma API
  description: ''
  version: 0.1.0
  contact:
    name: Nationaal Watersportdiploma Secretariaat
    email: info@nationaalwatersportdiploma.nl
    url: https://www.nationaalwatersportdiploma.nl/api
  license:
    name: AGPL-3.0 license
    url: >-
      https://github.com/buchungapp/nationaal-watersportdiploma/blob/main/LICENSE

servers:
  - url: https://api.nwd.nl
    description: Production API

paths:
  /programs:
    get:
      operationId: get-programs
      summary: Retrieve a list of programs
      description: >-
        Retrieve a list of programs. The list will be paginated and the provided
        query parameters allow filtering the returned programs.
      tags:
        - Programs
      security:
        - token: []
      responses:
        '200':
          description: A list of programs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProgramSchema'

components:
  securitySchemes:
    token:
      type: http
      description: Default authentication mechanism
      scheme: bearer
      in: header

  schemas:
    ProgramSchema:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the program
        handle:
          type: string
          pattern: ^[a-z0-9\-]+$
          minLength: 3
          description: The unique handle of the program
        title:
          type: string
          nullable: true
          description: The title of the program
      required:
        - id
        - handle
        - title

  responses:
    forbidden:
      description: Forbidden
