openapi: 3.0.2

info:
  title: Nationaal Watersportdiploma API
  description: |-
    Nationaal Watersportdiploma API
  version: 0.1.0

servers:
- url: https://api.nationaalwatersportdiploma.nl
  description: Production server

paths:
  /healthz:
    get:
      operationId: healthCheck
      tags:
        - system
      summary: Health check endpoint
      description: Check if the API is up and running
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"

  /discipline:
    get:
      operationId: listDisciplines
      tags:
        - discipline
      summary: Lists all disciplines
      security:
        - token: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './models/discipline.yaml#/$defs/DisciplineModel'
        '401':
          description: Unauthorized

  /discipline/{discipline-key}:
    parameters:
      - in: path
        name: discipline-key
        required: true
        schema:
          $ref: './fields.yaml#/$defs/HandleOrId'
    get:
      operationId: retrieveDiscipline
      tags:
        - discipline
      summary: Retrieves a single discipline
      security:
        - token: []
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: './models/discipline.yaml#/$defs/DisciplineModel'
        '401':
          description: Unauthorized
        '404':
          description: Not Found

components:
  securitySchemes:
    token:
      type: http
      description: Default authentication mechanism
      scheme: bearer
