openapi: 3.0.2

info:
  title: Nationaal Watersport Diploma API
  description: |-
    Nationaal Watersport Diploma API
  version: 0.1.0

paths:
  /main-category:
    get:
      operationId: get-main-categories
      summary: Get main get-main-categories
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/main-category"
    post:
      operationId: create-main-category
      summary: Create an new main category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/main-category-fields"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main-category"

  /sub-category/{main-category-id}:
    parameters:
      - name: main-category-id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/entity-id"
    get:
      operationId: get-sub-categories
      summary: Get sub categories in a main category
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/main-category"
    post:
      operationId: create-sub-category
      summary: Create an new sub category in a main category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sub-category-fields"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sub-category"

components:
  schemas:
    #entity schemas

    main-category:
      description: |-
        Full main category entity
      $ref: "#/components/schemas/main-category-fields"
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/entity-id"

    main-category-fields:
      description: |-
        Main category editable fields
      type: object
      required:
        - name
      properties:
        name:
          $ref: "#/components/schemas/entity-name"
        description:
          $ref: "#/components/schemas/entity-description"

    sub-category:
      description: |-
        Full sub category entity
      $ref: "#/components/schemas/sub-category-fields"
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/entity-id"

    sub-category-fields:
      description: |-
        Sub category entity editable fields
      type: object
      required:
        - name
      properties:
        name:
          $ref: "#/components/schemas/entity-name"
        description:
          $ref: "#/components/schemas/entity-description"

    # field schemas

    entity-id:
      description: |-
        Key of an entity
      type: integer
      # exclusiveMinimum: 0

    entity-name:
      description: |-
        The name of an entity
      type: string
      minLength: 1
      maxLength: 100

    entity-description:
      description: |-
        Description of an entity
      type: string
      minLength: 1
      maxLength: 100

  securitySchemes:
    api-key:
      type: apiKey
      name: api-key
      in: header
