import { useQuery } from "@nawadi/core";
import { schema as s } from "@nawadi/db";
import {
  COMPETENCY_AFKRUISEN_ID,
  COMPETENCY_GEDRAGSREGELS_ID,
  COMPETENCY_GESLEEPT_WORDEN_ID,
  COMPETENCY_GEWICHTSTRIM_ID,
  COMPETENCY_GIJPEN_ID,
  COMPETENCY_KNOPEN_EN_LIJNEN_ID,
  COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
  COMPETENCY_METEOROLOGIE_ID,
  COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
  COMPETENCY_ONDERDELEN_ID,
  COMPETENCY_OPKRUISEN_ID,
  COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
  COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
  COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
  COMPETENCY_OVERSTAG_ID,
  COMPETENCY_POSITIE_EN_HOUDING_ID,
  COMPETENCY_REGLEMENTEN_ID,
  COMPETENCY_REVEN_ID,
  COMPETENCY_ROERBEDIENING_ID,
  COMPETENCY_SCHOOTBEDIENING_ID,
  COMPETENCY_VAARTERMEN_ID,
  COMPETENCY_VEILIGHEID_ID,
  COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
  COMPETENCY_WINDORIENTATIE_ID,
  COMPETENCY_ZEILSTANDEN_ID,
  COMPETENCY_ZEILTRIM_ID,
  COMPETENCY_ZWAARDBEDIENING_ID,
} from "./competencies.js";
import { GEAR_TYPE_LASER_PICO_ID } from "./gear-types.js";
import {
  MODULE_BASIS_ID,
  MODULE_HANDELING_ID,
  MODULE_THEORIE_EXTRA_ID,
  MODULE_THEORIE_ID,
} from "./modules.js";
import {
  PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
  PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
} from "./programs.js";

export const CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aabb";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaaa";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaab";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaac";

export const CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaad";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaae";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48aaaf";
export const CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48bbbb";

export const CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48bbba";
export const CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48bbab";
export const CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48bbbc";
export const CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID =
  "b1f95621-a31c-4f0d-a37f-80cccc48bbbd";

export async function addCurriculum() {
  const query = useQuery();

  await query.insert(s.curriculum).values([
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },

    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },

    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
    {
      id: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      programId: PROGRAM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      revision: "2401",
      startedAt: new Date("2021-01-01").toISOString(),
    },
  ]);

  // Gear Types
  await query.insert(s.curriculumGearLink).values([
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      gearTypeId: GEAR_TYPE_LASER_PICO_ID,
    },
  ]);

  // Modules
  await query.insert(s.curriculumModule).values([
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
    },
  ]);

  await query.insert(s.curriculumCompetency).values([
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZWAARDBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JEUGD_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_METEOROLOGIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZWAARDBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_JONGEREN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_1_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_2_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_METEOROLOGIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZWAARDBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_3_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_EXTRA_ID,
      competencyId: COMPETENCY_WEDSTRIJDZEILEN_THEORIE_ID,
      isRequired: false,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_REGLEMENTEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VAARTERMEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_ONDERDELEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_VEILIGHEID_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KRACHTEN_OP_HET_SCHIP_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_KNOPEN_EN_LIJNEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_GEDRAGSREGELS_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_THEORIE_ID,
      competencyId: COMPETENCY_METEOROLOGIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OVERSTAG_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_AFKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPVANGEN_VAN_WINDVLAGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_OPKRUISEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_HANDELING_ID,
      competencyId: COMPETENCY_GIJPEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ROERBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_WINDORIENTATIE_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GESLEEPT_WORDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OMSLAAN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPTUIGEN_EN_AFTUIGEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_GEWICHTSTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILTRIM_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_OPRICHTEN_VAN_DE_BOOT_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZWAARDBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_SCHOOTBEDIENING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_POSITIE_EN_HOUDING_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_ZEILSTANDEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
    {
      curriculumId: CURRICULUM_ZWAARDBOOT_1_MANS_VOLWASSENEN_4_ID,
      moduleId: MODULE_BASIS_ID,
      competencyId: COMPETENCY_REVEN_ID,
      isRequired: true,
      requirement: "Lorum ipsum",
    },
  ]);
}
