"use client";

import {
  ArchiveBoxArrowDownIcon,
  ArrowPathIcon,
  XMarkIcon,
} from "@heroicons/react/20/solid";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import type { AiChatErrorRetryRenderer } from "~/app/_components/ai-chat";

// Small client-side helpers for triggering compaction from various UI
// surfaces (menu item, warn banner, error-banner CTA). The actual
// work all happens in one server endpoint — these just POST there
// and refresh the route so the new summary + fold-away markers
// render.
//
// Shared `useCompact` hook below is the single source of truth for
// the fetch + error handling + post-success refresh. Components
// pick the surface; the hook owns behaviour.

function useCompact({ chatId }: { chatId: string }) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const run = (onDone?: () => void) => {
    setError(null);
    startTransition(async () => {
      try {
        const res = await fetch(`/api/leercoach/chat/${chatId}/compact`, {
          method: "POST",
        });
        if (!res.ok) {
          const body = (await res.json().catch(() => null)) as {
            error?: string;
          } | null;
          setError(body?.error ?? `HTTP ${res.status}`);
          return;
        }
        // Successful compaction changes the server-rendered history
        // (adds a summary row, flips compactedIntoId on several rows).
        // router.refresh re-runs the server component so the new
        // state flows into ChatShell's initialMessages.
        router.refresh();
        onDone?.();
      } catch (e) {
        setError(e instanceof Error ? e.message : "Onbekende fout");
      }
    });
  };

  return { run, isPending, error, clearError: () => setError(null) };
}

// ---- Menu-item trigger ----
//
// Goes into the ⋮ ActionsMenu alongside "Scope wijzigen". Clicking
// immediately fires compaction — no confirmation dialog, because the
// operation is non-destructive (all messages remain in the DB, just
// marked as folded) and the summary can always be re-generated by
// running compaction again on newer messages.

export function CompactMenuItem({
  chatId,
  onClose,
  disabled,
}: {
  chatId: string;
  /** Closes the parent Menu. Passed from ActionsMenuItem's onClick. */
  onClose: () => void;
  /** Rendered disabled when the chat is too short to compact. */
  disabled?: boolean;
}) {
  const { run, isPending } = useCompact({ chatId });

  return (
    <button
      type="button"
      onClick={() => {
        if (disabled) return;
        onClose();
        run();
      }}
      disabled={disabled || isPending}
      className="flex w-full items-start gap-2.5 rounded-lg px-3 py-2 text-left text-sm text-slate-700 transition-colors hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <ArchiveBoxArrowDownIcon
        aria-hidden="true"
        className="mt-0.5 size-4 shrink-0 text-slate-400"
      />
      <span className="flex min-w-0 flex-col">
        <span className="font-medium text-slate-900">
          {isPending ? "Comprimeren…" : "Gesprek comprimeren"}
        </span>
        <span className="text-xs text-slate-500">
          Vat oudere berichten samen. Je concepten blijven bewaard.
        </span>
      </span>
    </button>
  );
}

// ---- Auto-warn banner ----
//
// Rendered above the message list when server-side token estimation
// crosses CONTEXT_WARN_TOKEN_THRESHOLD. Soft amber, dismissible, with
// a primary "Nu comprimeren" button. Dismissal is purely visual
// (useState) — the next refresh shows it again if still warranted,
// and on a successful compaction it disappears because the token
// estimate drops.

export function CompactWarnBanner({ chatId }: { chatId: string }) {
  const [dismissed, setDismissed] = useState(false);
  const { run, isPending, error } = useCompact({ chatId });
  if (dismissed) return null;
  return (
    <div
      // `aria-live="polite"` because this appears async (after a long
      // turn crosses the threshold mid-session). We want screen
      // readers to notice but not interrupt.
      aria-live="polite"
      className="flex flex-wrap items-center gap-2 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900"
    >
      <span className="flex-1 min-w-0">
        Dit gesprek nadert de limiet. Comprimeer nu om verder te kunnen zonder
        je concepten te verliezen.
        {error ? (
          <span className="mt-0.5 block text-xs font-medium text-red-700">
            {error}
          </span>
        ) : null}
      </span>
      <div className="flex shrink-0 items-center gap-1">
        <button
          type="button"
          onClick={() => run()}
          disabled={isPending}
          className="inline-flex items-center gap-1 rounded-md border border-amber-400 bg-white px-2 py-1 text-xs font-semibold text-amber-900 shadow-sm transition-colors hover:bg-amber-100 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {isPending ? (
            <ArrowPathIcon
              className="size-3.5 animate-spin"
              aria-hidden="true"
            />
          ) : null}
          <span>{isPending ? "Comprimeren…" : "Nu comprimeren"}</span>
        </button>
        <button
          type="button"
          onClick={() => setDismissed(true)}
          aria-label="Banner sluiten"
          className="inline-flex size-6 items-center justify-center rounded-md text-amber-700 transition-colors hover:bg-amber-100 hover:text-amber-900"
        >
          <XMarkIcon className="size-4" aria-hidden="true" />
        </button>
      </div>
    </div>
  );
}

// ---- Context-limit error detection + compact-and-retry renderer ----
//
// Anthropic returns a "prompt is too long: N tokens > M maximum" error
// when the combined history + system + tool definitions exceed the
// model's context window. We pattern-match on the message body since
// the error class doesn't surface a distinct code through the gateway.
// Fallback: any error message containing "too long" or a "token" +
// "limit/maximum" combination.

function isContextLimitError(error: Error): boolean {
  const m = (error.message ?? "").toLowerCase();
  if (m.includes("too long")) return true;
  if (m.includes("context") && m.includes("limit")) return true;
  if (m.includes("tokens") && m.includes("maximum")) return true;
  return false;
}

/**
 * Swaps the generic "Probeer opnieuw" button in AiChat's ErrorBanner
 * for a "Comprimeer en probeer opnieuw" button when the error is a
 * context-limit. On any other error, returns null to let the default
 * retry render.
 *
 * The factory takes the chatId so it can build its own compaction
 * call without needing a provider. Consumers pass
 * `renderErrorAction={buildCompactAndRetryRenderer(chatId)}` to
 * AiChatWindow's errorRetryRenderer prop.
 */
export function buildCompactAndRetryRenderer(
  chatId: string,
): AiChatErrorRetryRenderer {
  // Explicit function + displayName keeps the react/display-name lint
  // happy (it flags anonymous arrow returns from factories that the
  // linter suspects are components).
  function CompactAndRetryAction({
    error,
    defaultRetry,
    isLoading,
  }: Parameters<AiChatErrorRetryRenderer>[0]) {
    if (!isContextLimitError(error)) return null;
    return (
      <CompactAndRetryButton
        chatId={chatId}
        defaultRetry={defaultRetry}
        isLoading={isLoading}
      />
    );
  }
  return CompactAndRetryAction;
}

function CompactAndRetryButton({
  chatId,
  defaultRetry,
  isLoading,
}: {
  chatId: string;
  defaultRetry: () => void;
  isLoading: boolean;
}) {
  const { run, isPending, error } = useCompact({ chatId });
  return (
    <div className="flex flex-col items-end gap-1">
      <button
        type="button"
        onClick={() =>
          // Compact first, then replay the last turn via the standard
          // regenerate(). router.refresh() inside useCompact feeds the
          // new message state to useChat, so regenerate() sees the
          // compacted history.
          run(() => defaultRetry())
        }
        disabled={isPending || isLoading}
        className="inline-flex items-center gap-1 rounded-lg border border-red-300 bg-white px-3 py-1.5 text-xs font-semibold text-red-800 shadow-sm transition-colors hover:border-red-400 hover:bg-red-100 disabled:cursor-not-allowed disabled:opacity-60"
      >
        {isPending ? (
          <ArrowPathIcon className="size-3.5 animate-spin" aria-hidden="true" />
        ) : (
          <ArchiveBoxArrowDownIcon aria-hidden="true" className="size-3.5" />
        )}
        <span>
          {isPending ? "Comprimeren…" : "Comprimeer en probeer opnieuw"}
        </span>
      </button>
      {error ? <span className="text-[11px] text-red-700">{error}</span> : null}
    </div>
  );
}
