on:
  pull_request: {}

jobs:
  api-docs:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      # - run: corepack enable
      - uses: actions/checkout@v4
      - run: pnpm run initialize
      - uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: generated/api-docs
