on:
  pull_request: {}

jobs:
  api-docs:
    strategy:
      matrix:
        node-version: [22]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - uses: actions/checkout@v4
      - run: pnpm run initialize
      - uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: generated/api-docs
