on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - packages/**

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run spelling
