on:
  pull_request: {}

jobs:
  formatting:
    strategy:
      matrix:
        node-version: [22]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      # - run: corepack enable
      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile --workspace-root
      - run: pnpm run formatting

  spelling:
    strategy:
      matrix:
        node-version: [22]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile --workspace-root
      - run: pnpm run spelling
