on:
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      # - run: corepack enable
      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile --workspace-root
      - run: pnpm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      # - run: corepack enable
      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile --workspace-root
      - run: pnpm run spelling
