on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - fixtures/**
      - packages/**

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    services:
      postgres:
        image: supabase/postgres:15.1.1.5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      PGURI: "postgres://postgres:postgres@postgres:5432/postgres"
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm --recursive run build
      - run: pnpm --recursive test

  audit:
    runs-on: ubuntu-latest
    container: node:21.5.0-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm audit
